spring.application.name=demo

# Tell Spring how to locate your local XAMPP MySQL database instance
spring.datasource.url=jdbc:mysql://localhost:3306/CVUT
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keeps your database connection pool steady and optimized in the background
spring.datasource.hikari.maximum-pool-size=10